// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJG0NSYFoK0LYGjaWcXAiYMXADyX6Bi_k',
    appId: '1:1008172033913:web:c0df0565ec3550dafe31a8',
    messagingSenderId: '1008172033913',
    projectId: 'busy-bee-7e457',
    authDomain: 'busy-bee-7e457.firebaseapp.com',
    storageBucket: 'busy-bee-7e457.firebasestorage.app',
    measurementId: 'G-ZB8S0HEFVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsLjMj4Tbii7b4_OthaJf01k2M6EKb3nI',
    appId: '1:1008172033913:android:a0571859aa914fb0fe31a8',
    messagingSenderId: '1008172033913',
    projectId: 'busy-bee-7e457',
    storageBucket: 'busy-bee-7e457.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MmfbZwyl4L4oG-Q2B2e10XxSgrbvBJs',
    appId: '1:1008172033913:ios:ba5963a9bd7cf832fe31a8',
    messagingSenderId: '1008172033913',
    projectId: 'busy-bee-7e457',
    storageBucket: 'busy-bee-7e457.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-MmfbZwyl4L4oG-Q2B2e10XxSgrbvBJs',
    appId: '1:1008172033913:ios:ba5963a9bd7cf832fe31a8',
    messagingSenderId: '1008172033913',
    projectId: 'busy-bee-7e457',
    storageBucket: 'busy-bee-7e457.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJG0NSYFoK0LYGjaWcXAiYMXADyX6Bi_k',
    appId: '1:1008172033913:web:9a4a5c34eba9e72dfe31a8',
    messagingSenderId: '1008172033913',
    projectId: 'busy-bee-7e457',
    authDomain: 'busy-bee-7e457.firebaseapp.com',
    storageBucket: 'busy-bee-7e457.firebasestorage.app',
    measurementId: 'G-EBTQLPT0RJ',
  );
}
